do not recreate history file
if the history file is symlinked, most likely as dotfiles, recreating
means we lose that link. So instead of recreating the history file, we
can redirect the contents and overwrite it instead

diff --git a/ani-cli b/ani-cli
--- a/ani-cli
+++ b/ani-cli
@@ -314,7 +314,8 @@ update_history() {
         cp "$histfile" "${histfile}.new"
         printf "%s\t%s\t%s\n" "$ep_no" "$id" "$title" >>"${histfile}.new"
     fi
-    mv "${histfile}.new" "$histfile"
+    cat "${histfile}.new" >"$histfile"
+    rm "${histfile}.new"
 }
 
 download() {
@@ -563,8 +564,8 @@ done
 printf "\33[2K\r\033[1;34mChecking dependencies...\033[0m\n"
 dep_ch "curl" "sed" "grep" || true
 case "$(uname -o 2>/dev/null)" in
-    *ndroid*) command -v openssl >/dev/null || die 'Program "openssl" not found. On Termux, install with: pkg install openssl-tool' ;;
-    *) dep_ch "openssl" || true ;;
+*ndroid*) command -v openssl >/dev/null || die 'Program "openssl" not found. On Termux, install with: pkg install openssl-tool' ;;
+*) dep_ch "openssl" || true ;;
 esac
 [ "$skip_intro" = 1 ] && (dep_ch "ani-skip" || true)
 if [ -z "$ANI_CLI_NON_INTERACTIVE" ]; then dep_ch fzf || true; fi
